Demo: ParametrizeCamera_LoadAndSave.cpp
	g++ -g -o ParametrizeCamera_LoadAndSave ParametrizeCamera_LoadAndSave.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl 
	

clean:
	rm ParametrizeCamera_LoadAndSave -rf
