Demo: GrabImage.cpp
	g++ -g -m32 -o GrabImage GrabImage.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm GrabImage -rf
