Demo: Grab_ImageCallback.cpp
	g++ -g -m32 -o Grab_ImageCallback Grab_ImageCallback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl
	

clean:
	rm Grab_ImageCallback -rf
