pos:
    #预测维度
    vector_len: 2
    #粒子数
    num_particle: 500
    #过程噪声,可以增加粒子多样性,提高滤波器鲁棒性,增大后可以提高滤波器响应速度,但也会造成坐标抖动
    process_noise: [0.015, 0,
                    0, 0.015]
    #观测噪声, 影响重要性密度函数,会改变粒子权重,增大可以平滑预测值,但也会增大预测延迟
    observe_noise: [0.02, 0,
                    0, 0.02]

v:
    #预测维度
    vector_len: 2
    #粒子数
    num_particle: 1000
    #过程噪声,可以增加粒子多样性,提高滤波器鲁棒性,增大后可以提高滤波器响应速度,但也会造成坐标抖动
    process_noise: [0.1, 0,
                    0, 0.1]
    #观测噪声, 影响重要性密度函数,会改变粒子权重,增大可以平滑预测值,但也会增大预测延迟
    observe_noise: [0.2, 0,
                    0, 0.2]

buff:
    #预测维度
    vector_len: 1
    #粒子数
    num_particle: 400
    #过程噪声,可以增加粒子多样性,提高滤波器鲁棒性,增大后可以提高滤波器响应速度,但也会造成坐标抖动
    process_noise: [0.1]
    #观测噪声, 影响重要性密度函数,会改变粒子权重,增大可以平滑预测值,但也会增大预测延迟
    observe_noise: [0.15] 