Demo: ChunkData.cpp
	g++ -g -m32 -o ChunkData ChunkData.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm ChunkData -rf
