Demo: Trigger_ImageCallback.cpp
	g++ -g -m32 -o Trigger_ImageCallback Trigger_ImageCallback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm Trigger_ImageCallback -rf
