<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/common/omni_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="chassis_radius" value="0.196"/>
    <xacro:property name="wheel_offset_z" value="-0.04373"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="12.326"/>
                <origin xyz="-0.000932  -0.000668  -0.01"/>
                <inertia ixx="1.924e-1" ixy="-6.458e-4" ixz="5.951352e-3" iyy="2.473e-1"
                         iyz="-7.22e-4" izz="3.187e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://robot_description/meshes/standard/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.392 0.392 0.2"/>
                </geometry>
            </collision>
        </link>

        <xacro:omni_wheel prefix="left_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${3*pi/4}" roller_type="${roller_type}"
                          max_effort="5" max_velocity="50"
        />
        <xacro:omni_wheel prefix="right_front" connected_to="base_link"
                          wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/4}" roller_type="${roller_type}"
                          max_effort="5" max_velocity="50"
        />
        <xacro:omni_wheel prefix="left_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-3*pi/4}" roller_type="${roller_type}"
                          max_effort="5" max_velocity="50"
        />
        <xacro:omni_wheel prefix="right_back" connected_to="base_link"
                          wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                          wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/4}" roller_type="${roller_type}"
                          max_effort="5" max_velocity="50"
        />
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>
