#!/bin/sh
### BEGIN INIT INFO
# Provides:          DriverServer
# Required-Start:    $remote_fs $syslog $local_fs
# Required-Stop:     $remote_fs $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: driver self-starting
# Description:       DriverServer is a daemon to self-starting driver server.
### END INIT INFO

SDK_HOME=/opt/MVS

# Start the Driver Server
start() 
{
	IMAGEFILTER_LOADED=`lsmod | grep -o gevfilter`
        if [ "$IMAGEFILTER_LOADED" != "gevfilter" ]; then
                if [ ! -f $SDK_HOME/driver/gevfilter.ko ]; then
                        if [ -f $SDK_HOME/driver/build.sh ]; then
                                $SDK_HOME/driver/build.sh >/dev/null 2>&1
                        fi
                fi

                if [ -f $SDK_HOME/driver/load.sh ]; then
                        $SDK_HOME/driver/load.sh >/dev/null 2>&1
                fi
        fi
	
}

# Main logic
case "$1" in
    start)
        start
        ;;
  *)
    echo $"Usage: $0 {start}"
    exit 1
esac
exit 0
