<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.4"/>
    <xacro:property name="wheel_base" value="0.4"/>
    <xacro:property name="wheel_offset_z" value="-0.068374"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="10.34269"/>
                <origin xyz="-0.003691 -0.001885 0.024404"/>
                <inertia ixx="1.952E-01" ixy="-1.504E-03" ixz="5.871E-03" iyy="3.011E-01"
                         iyz="-1.077E-03" izz="4.074E-01"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://robot_description/meshes/hero/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://robot_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>


        <xacro:mecanum_wheel prefix="left_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"
                             max_effort="5" max_velocity="50"/>
        <xacro:mecanum_wheel prefix="right_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"
                             max_effort="5" max_velocity="50"/>
        <xacro:mecanum_wheel prefix="left_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"
                             max_effort="5" max_velocity="50"/>
        <xacro:mecanum_wheel prefix="right_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"
                             max_effort="5" max_velocity="50"/>
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>
