Demo: ReconnectDemo.cpp
	g++ -g -m32 -o ReconnectDemo ReconnectDemo.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm ReconnectDemo -rf
