Demo: ParametrizeCamera_LoadAndSave.cpp
	g++ -g -m32 -o ParametrizeCamera_LoadAndSave ParametrizeCamera_LoadAndSave.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl 
	

clean:
	rm ParametrizeCamera_LoadAndSave -rf
