Demo: MultiCast.cpp
	g++ -g -m32 -o MultiCast MultiCast.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread 
	

clean:
	rm MultiCast -rf
