Demo: ParametrizeCamera_FileAccess.cpp
	g++ -g -m32 -o ParametrizeCamera_FileAccess ParametrizeCamera_FileAccess.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm ParametrizeCamera_FileAccess -rf
