Demo: Trigger_Image.cpp
	g++ -g -m32 -o Trigger_Image Trigger_Image.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread
	

clean:
	rm Trigger_Image -rf
