Demo: ImageProcess.cpp
	g++ -g -m32 -o ImageProcess ImageProcess.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl 
	

clean:
	rm ImageProcess -rf
