Demo: GrabMultipleCamera.cpp
	g++ -g -o GrabMultipleCamera GrabMultipleCamera.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm GrabMultipleCamera -rf
