Demo: GrabImage_HighPerformance.cpp
	g++ -g -m32 -o GrabImage_HighPerformance GrabImage_HighPerformance.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread 
	

clean:
	rm GrabImage_HighPerformance -rf
