#!/bin/sh
#
#  Start / Stop the MvLogServer daemon.
#
# chkconfig: 2345 90 60
# description: MvLogServer

### BEGIN INIT INFO
# Provides:          MvLogServer
# Required-Start:    $remote_fs $syslog $local_fs
# Required-Stop:     $remote_fs $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start log server at boot time
# Description:       LogServer is a daemon to self-startint log server.
### END INIT INFO
# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0


SDK_HOME=${MVCAM_SDK_PATH}
DAEMON="${SDK_HOME}/logserver/MvLogServer"
NAME="MvLogServer"
PIDFILE="/var/run/MvLogServer.pid"

exec_Script()
{
	IMAGEFILTER_LOADED=`lsmod | grep -o gevfilter`
	if [ "$IMAGEFILTER_LOADED" != "gevfilter" ]; then
		if [ ! -f $SDK_HOME/driver/gevfilter.so ]; then
			if [ -f $SDK_HOME/driver/build.sh ]; then
				$SDK_HOME/driver/build.sh
			fi
		fi
		
		if [ -f $SDK_HOME/driver/load.sh ]; then
			$SDK_HOME/driver/load.sh
		fi
	fi
	
}

start () {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privileges."
		exit 4
	fi
    	#[ -x $DAEMON ] || exit 5

	echo -n "Starting $NAME: "
   	daemon $DAEMON
 	RETVAL=$?
	echo
	[ $RETVAL = 0 ]
	
	return 0
}

stop () {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privileges."
		exit 4
	fi

	# stop daemon
	echo -n $"Stopping $NAME: "
	killproc $NAME
	RETVAL=$?
	echo
	[ $RETVAL = 0 ]
	return 0
}

restart() {
	stop
	sleep 1
	start	
	return 0
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	status)
		status -p $PIDFILE $NAME
		RETVAL=$?
        ;;
	*)

	echo $"Usage: $NAME {start|stop|restart|status}" 
	exit 2
esac

exit $RETVAL
