Demo: ConnectSpecCamera.cpp
	g++ -g -o ConnectSpecCamera ConnectSpecCamera.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm ConnectSpecCamera -rf
