Demo: ReconnectDemo.cpp
	g++ -g -o ReconnectDemo ReconnectDemo.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm ReconnectDemo -rf
