Demo: Grab_ImageCallback.cpp
	g++ -g -o Grab_ImageCallback Grab_ImageCallback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl
	

clean:
	rm Grab_ImageCallback -rf
